In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
ring_ones = pd.read_csv('../LOTR_Code/Resources/lotr_characters.csv')
ring_ones.head(10)

,birth,death,gender,hair,height,name,race,realm,spouse
0,NaN,NaN,Female,NaN,NaN,Adanel,Men,NaN,Belemir
1,TA 2978,"February 26 ,3019",Male,Dark (book) Light brown (movie),NaN,Boromir,Men,NaN,NaN
2,NaN,"March ,3019",Male,NaN,NaN,Lagduf,Orcs,NaN,NaN
3,TA 280,TA 515,Male,NaN,NaN,Tarcil,Men,Arnor,Unnamed wife
4,NaN,NaN,Male,NaN,NaN,Fire-drake of Gondolin,Dragon,NaN,NaN
5,SA 2709,SA 2962,Male,NaN,NaN,Ar-Adûnakhôr,Men,Númenor,Unnamed wife
6,NaN,NaN,Male,NaN,NaN,Annael,Elves,NaN,NaN
7,YT,FA 455,Male,Golden,NaN,Angrod,Elves,NaN,Eldalótë
8,NaN,NaN,NaN,NaN,NaN,Angrim,NaN,NaN,NaN
9,SA 3219,SA 3440,Male,NaN,NaN,Anárion,Men,Gondor,Unnamed wife

In [14]:
ring_ones.dropna()

,birth,death,gender,hair,height,name,race,realm,spouse
125,SA 3209,TA 2,Male,Black,Very tall almost 7'1,Isildur,Men,"Arnor,Gondor",Unnamed wife
134,"YT, and perhaps firstborn",Still Alive,Male,Probably Golden,Tall,Ingwë,Elves,"Valinor,Taniquetil",Unnamed wife
166,YT,FA 400,Male,Dark,Tall,Eöl,Elves,Nan Elmoth,Aredhel
186,TA 2990,FO 63,Male,Dirty blond,Tall-6'6,omer,Men,Rohan,Lothíriel after the War of the Ring
194,FA 532,"Still alive; departed to ,Aman, on ,September ...",Male,Dark,Tall,Elrond,Half-elven,Rivendell,Celebrían
204,SA 3119,SA 3441,Male,Brown,"7' 10""",Elendil,Men,"Arnor,Gondor",Unnamed wife
530,YT,"Still alive, departed over the sea in the earl...",Male,Silver,Tall,Celeborn,Elves,"Eregion,Lothlórien,Caras Galadhon",Galadriel
620,TA 2925,TA 3007,Male,Brown (film),"1.76m / 5'9"" (film)",Bain,Men,Dale,Unnamed wife
686,YT 1362,"Still alive: Departed over the sea on ,Septemb...",Female,Golden,Tall,Galadriel,Elves,"Eregion,Lothlórien,Caras Galadhon",Celeborn
692,YT 1169,YT 1497,Male,Raven,Tall,Fëanor,Elves,"Tirion,Formenos",Nerdanel
795,First Age,"Presumably departed to ,Aman",Male,Golden,Tall,Thranduil,Elves,"Woodland Realm,Mirkwood",Unnamed wife
802,YT 1050,FA 502,Male,Silver,"Tallest of the Elven-folk, 8'2""",Thingol,Elves,Doriath,Melian
873,"March 1 ,2931",FO 120,Male,Dark,"198cm (6'6"")",Aragorn II Elessar,Men,"Reunited Kingdom,Arnor,Gondor",Arwen