In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
ring_ones = pd.read_csv('../Lord_of_the_Rings/Resources/lotr_characters.csv')
ring_ones

,birth,death,gender,hair,height,name,race,realm,spouse
0,NaN,NaN,Female,NaN,NaN,Adanel,Men,NaN,Belemir
1,TA 2978,"February 26 ,3019",Male,Dark (book) Light brown (movie),NaN,Boromir,Men,NaN,NaN
2,NaN,"March ,3019",Male,NaN,NaN,Lagduf,Orcs,NaN,NaN
3,TA 280,TA 515,Male,NaN,NaN,Tarcil,Men,Arnor,Unnamed wife
4,NaN,NaN,Male,NaN,NaN,Fire-drake of Gondolin,Dragon,NaN,NaN
...,...,...,...,...,...,...,...,...,...
906,"Mid ,First Age",FA 495,Female,NaN,NaN,Aerin,Men,NaN,Brodda
907,NaN,NaN,NaN,NaN,NaN,Aerandir,NaN,NaN,NaN
908,"YT during the ,Noontide of Valinor",FA 455,Male,Golden,NaN,Aegnor,Elves,NaN,"Loved ,Andreth but remained unmarried"
909,TA 2917,TA 3010,Male,NaN,NaN,Adrahil II,Men,NaN,Unnamed wife
910,"Before ,TA 1944","Late ,Third Age",Male,NaN,NaN,Adrahil I,Men,NaN,NaN

In [4]:
ring_ones.dropna()

,birth,death,gender,hair,height,name,race,realm,spouse
125,SA 3209,TA 2,Male,Black,Very tall almost 7'1,Isildur,Men,"Arnor,Gondor",Unnamed wife
134,"YT, and perhaps firstborn",Still Alive,Male,Probably Golden,Tall,IngwÃ«,Elves,"Valinor,Taniquetil",Unnamed wife
166,YT,FA 400,Male,Dark,Tall,EÃ¶l,Elves,Nan Elmoth,Aredhel
186,TA 2990,FO 63,Male,Dirty blond,Tall-6'6,omer,Men,Rohan,LothÃ­riel after the War of the Ring
194,FA 532,"Still alive; departed to ,Aman, on ,September ...",Male,Dark,Tall,Elrond,Half-elven,Rivendell,CelebrÃ­an
204,SA 3119,SA 3441,Male,Brown,"7' 10""",Elendil,Men,"Arnor,Gondor",Unnamed wife
530,YT,"Still alive, departed over the sea in the earl...",Male,Silver,Tall,Celeborn,Elves,"Eregion,LothlÃ³rien,Caras Galadhon",Galadriel
620,TA 2925,TA 3007,Male,Brown (film),"1.76m / 5'9"" (film)",Bain,Men,Dale,Unnamed wife
686,YT 1362,"Still alive: Departed over the sea on ,Septemb...",Female,Golden,Tall,Galadriel,Elves,"Eregion,LothlÃ³rien,Caras Galadhon",Celeborn
692,YT 1169,YT 1497,Male,Raven,Tall,FÃ«anor,Elves,"Tirion,Formenos",Nerdanel
795,First Age,"Presumably departed to ,Aman",Male,Golden,Tall,Thranduil,Elves,"Woodland Realm,Mirkwood",Unnamed wife
802,YT 1050,FA 502,Male,Silver,"Tallest of the Elven-folk, 8'2""",Thingol,Elves,Doriath,Melian
873,"March 1 ,2931",FO 120,Male,Dark,"198cm (6'6"")",Aragorn II Elessar,Men,"Reunited Kingdom,Arnor,Gondor",Arwen

In [6]:
ring_lineup = ring_ones.groupby(by="race").count()
ring_lineup

                  birth  death  gender  hair  height  name  realm  spouse
race
Ainur                24     21      24     4       6    24     10      13
Ainur,Maiar           1      0       1     0       0     1      0       0
Balrog                1      1       1     1       0     1      0       0
Black Uruk            1      0       1     0       1     1      1       0
Dragon                0      0       1     0       0     1      0       0
Dragons               3      4       5     0       2     5      1       0
DrÃºedain              1      0       1     1       1     1      0       0
Dwarf                 1      1       1     0       0     1      0       0
Dwarven               1      1       1     0       0     1      0       0
Dwarves              39     37      42    10       2    42     12      17
Eagle                 1      1       1     0       0     1      0       0
Eagles                0      0       1     0       0     1      0       0
Elf                   2      3       3     2       0     3      1       0
Elves                70     66     100    50      23   103     24      56
Elves,Maiar           1      1       1     1       0     1      0       1
Elves,Noldor          0      1       1     1       0     1      0       0
Ents                  1      1       2     2       1     2      0       0
Ents,Onodrim          1      0       1     1       1     1      0       1
Goblin,Orc            0      1       1     0       1     1      0       0
God                   0      0       1     1       1     1      1       0
Great Eagles          1      1       2     0       1     2      0       0
Great Spiders         1      2       2     0       2     2      1       0
Half-elven            7      6       7     4       1     7      3       6
Half-elven,Men        1      1       1     1       0     1      1       1
Hobbit               13      9      16     4       5    16      1      13
Hobbits             125     83     126    14       5   126      8      84
Horse                 0      0       0     0       0     1      0       0
Maiar                 4      3       4     4       1     4      1       0
Maiar,Balrog          1      1       1     1       1     1      0       0
Maiar,Balrogs         1      1       1     0       0     1      0       0
Men                 383    319     386    57      28   388    118     266
Men,Rohirrim          1      1       1     0       0     1      1       0
Men,Skin-changer      1      1       1     1       1     1      0       0
Men,Undead            1      1       1     0       1     1      1       0
Men,Wraith            3      2       3     2       1     3      2       1
Orc                   0      4       4     1       1     4      2       0
Orc,Goblin            1      1       1     0       0     1      1       0
Orcs                  0      6       6     2       2     6      1       0
Raven                 1      0       1     0       0     1      0       0
Skin-changer          0      1       1     1       1     1      0       0
Stone-trolls          1      0       1     0       1     1      0       0
Uruk-hai              3      3       3     3       2     3      2       1
Uruk-hai,Orc          0      1       1     1       1     1      1       0
UrulÃ³ki               1      1       1     0       1     1      1       1
Vampire               0      1       1     0       0     1      0       0
Werewolves            1      2       2     1       1     2      1       0
Wolfhound             1      1       1     0       1     1      0       0